const os = require('os')
var arch = os.arch()
// var cpus = os.cpus()
var freemem = os.freemem()
var hostname = os.hostname()
var type = os.type()
var uptime = os.uptime()
var userInfo = os.userInfo()
console.log(arch)
// console.log(cpus)
console.log(freemem)
console.log(hostname)
console.log(type)
console.log(uptime)
console.log(userInfo)
